@UserManagement.API_HostAddress = https://localhost:5001


POST {{UserManagement.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "harshidkahar9@gmail.com",
  "password": "Harshid"
}

###

POST {{UserManagement.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Harshid",
  "lastName": "Kahar",
  "email": "harshidkahar9@gmail.com",
  "password": "Harshid"
}

###

GET {{UserManagement.API_HostAddress}}/api/auth/user?Id=C2DE54E8-87FF-40F2-8B32-13EAF611716E

###
